### ISSUE TITLE
Broke with Exordium

### ISSUE THREAD

**Issue by Arborsm** [yurisuika/Raised#79]
* Hm,I ported the mantle's extra heart renderer to my mod [ExtraHeartRenderHandler](https://github.com/Arborsm/ArborCore/blob/master/src/main/java/org/arbor/arborcore/client/ExtraHeartRenderHandler.java), but got crushed. Not good at forge events, need help :(

[25Dec2023 17:10:48.541] [Worker-ResourceReload-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLClientSetupEvent dispatch for modid raised
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:184) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThreadOrInit(RenderSystem.java:168) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at com.mojang.blaze3d.pipeline.TextureTarget.<init>(TextureTarget.java:8) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at dev.tr7zw.exordium.util.BufferedComponent.<init>(BufferedComponent.java:23) ~[exordium-forge-1.2.1-mc1.20.1.jar%23390!/:1.2.1-mc1.20.1]
	at net.minecraft.client.gui.Gui$Anonymous$3fe96e9b01954e678ae7edc00f8cfe6e.<init>(CrosshairMixin.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraft.client.gui.Gui.<init>(Gui.java:127) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.<init>(ForgeGui.java:69) ~[forge-1.20.1-47.2.18-universal.jar%23501!/:?]
	at dev.yurisuika.raised.client.gui.RaisedGui.<init>(RaisedGui.java:37) ~[raised-forge-1.20.1-3.1.0.jar%23456!/:?]
	at dev.yurisuika.raised.Raised$ClientModBusEvents.clientSetup(Raised.java:45) ~[raised-forge-1.20.1-3.1.0.jar%23456!/:?]
	at dev.yurisuika.raised.__ClientModBusEvents_clientSetup_FMLClientSetupEvent.invoke(.dynamic) ~[raised-forge-1.20.1-3.1.0.jar%23456!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.18.jar%23498!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.18.jar%23497!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by yurisuika** [comment]
#73 may have resolved your issue, try with the latest build of Raised and see if it works!

**Comment by yurisuika** [comment]
"Rendersystem called from wrong thread" makes it sound like `MinecraftClient.getInstance()` is getting called on the server? Looking at it I do not see why exactly.

I've tried building your mod to try to replicate the error myself but it is crashing from something in ChatMixin.

**Comment by Arborsm** [comment]
> "Rendersystem called from wrong thread" makes it sound like `MinecraftClient.getInstance()` is getting called on the server? Looking at it I do not see why exactly.
> 
> I've tried building your mod to try to replicate the error myself but it is crashing from something in ChatMixin.

I think it is gtceu broke, it need to remove the jar-in-jar on dev; and imma check what you mention

**Comment by Arborsm** [comment]
> "Rendersystem called from wrong thread" makes it sound like `MinecraftClient.getInstance()` is getting called on the server? Looking at it I do not see why exactly.
> 
> I've tried building your mod to try to replicate the error myself but it is crashing from something in ChatMixin.

weird, I added it to `Raised` and just works fine
![image](https://github.com/yurisuika/Raised/assets/44860537/8f78229a-e72d-4221-b4cf-85de996aedbb)

**Comment by Arborsm** [comment]
DAMN, It is `exordium` broke `Raised`

**Comment by Arborsm** [comment]
maybe I should make a issue there

**Comment by yurisuika** [comment]
Okay that would explain where the CrosshairMixin came from.

**Comment by Arborsm** [comment]
> Exordium

wrong mod? this: https://modrinth.com/mod/exordium

**Comment by yurisuika** [comment]
Ah I see it is the same but on the CurseForge page it says that Forge will not be supported.

**Comment by Arborsm** [comment]
hmm https://github.com/tr7zw/Exordium/issues/126
